### ISSUE TITLE
Author analysis GIScience vs. AGILE

### ISSUE THREAD

**Issue by nuest** [nuest/reproducible-research-at-giscience#2]
See https://github.com/nuest/reproducible-research-at-giscience/blob/master/author_analysis/BibTex_handling.ipynb

## Tasks

- [x] get notebook to work within the same Binder (uses `Dockerfile`) @nuest 
- [x] fix LaTeX artifact for Umlaut and special characters from the LIPIcs bibtex file, e.g. `{\"{o}}` (probably best handled by changing the bib file manually?) @nuest 
- [ ] redo retrieval @cgranell 

## Questions

- [x] @foost Can you clarify in the notebook where the file `GIScience_Conference_2018.bib` originates from? The other .bib files seem to be results of the Scopus search.

**Comment by nuest** [comment]
@foost Any idea why `worboys` appears several times in the list?

**Comment by cgranell** [comment]
I ran the search queries on Scopus. The AGILE query appears to retrieve all LNCG books (and individual papers) from 2007 to today. Results from the GIScience query are a bit odd. Two years do not works as expected: 2014 (3 records) and 2004 (1 record).

**Comment by nuest** [comment]
Thanks for checking Carlos - I think if we miss the full records only for two years (which are quite far apart) that is something we can live with.
